### ISSUE TITLE
Outlier in Lahiru's data

### ISSUE THREAD

**Issue by hrlai** [xp-song/allometree#1]
```
> subset(urbantrees, height > 40)
# A tibble: 1 x 3
  species                  diameter height
  <chr>                       <dbl>  <int>
1 Xanthostemon chrysanthus   0.0987     43
```

I am removing this outlier (plot `height ~ diameter` to see) because it's making the mixed-models hard to fit. Check?

**Comment by xp-song** [comment]
Yup you can remove it! In the [vignette for single species models](https://xp-song.github.io/allometree/articles/single-species_models.html) I show one possible way to remove the outlier. You could do it similarly for the mixed-effects model or choose to do it another way

**Comment by hrlai** [comment]
Yes, I almost forgot about this after such a long time. The problem is that outlier removal is a trickier for the mixed-effects model cf. single-species models... in the manuscript we did it by the same way as the single-species model, but for a user who wants to jump straight into mixed model, we need to come up with a way that is less dependent on the single-species model. Currently, the `uncooker` function takes in both the data and the single-species model list.

I'll return to this again.

**Comment by xp-song** [comment]
Removed outlier in commit [37346e1](https://github.com/xp-song/allometree/commit/37346e1147de17c917036535810d4c9c0220a808)
