### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by hrlai** [xp-song/allometree#2]
```
> devtools::install_github("xp-song/allometree")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`xp-song`) and repo name (`allometree`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

Any idea?

**Comment by xp-song** [comment]
The repo is still private, so you have to install it locally using 

`devtools::build() # build`
or
`devtools::install()  # install into R sys library (Cmd + Shift + B)`

Would you like to make the repo public now?

**Comment by hrlai** [comment]
No need to make it public until we're ready, will install locally now! (didn't know you could do it, d'oh)
